Repository bokzip/bokzip-backend, pull requests merged in 2021-08, with the labels that each got.

#1 [fix] Posts 지원대상,선정기준 등 추가
  src/main/java/bokzip/back/domain/Post.java
Labels: 피드백 요청, fix

#2 [feat] Posts 데이터 조회(Post에 대한 Service, Repository, Controller 추가)
  build.gradle
  src/main/java/bokzip/back/SpringConfig.java
  src/main/java/bokzip/back/configuration/DBConfig.java
  src/main/java/bokzip/back/controller/PostController.java
  src/main/java/bokzip/back/repository/PostRepository.java
  src/main/java/bokzip/back/repository/UserRepository.java
  src/main/java/bokzip/back/service/PostService.java
  src/main/java/bokzip/back/service/UserService.java
  src/test/java/bokzip/back/repository/PostRepositroyTest.java
  src/test/java/bokzip/back/service/PostServiceTest.java
Labels: 피드백 요청, feat

#5 [feat:#4] Generals, Scrpas 테이블 추가, Users, Posts 테이블 수정
  src/main/java/bokzip/back/domain/General.java
  src/main/java/bokzip/back/domain/PersonalInfo.java
  src/main/java/bokzip/back/domain/Post.java
  src/main/java/bokzip/back/domain/Scrap.java
  src/main/java/bokzip/back/domain/User.java
Labels: 피드백 요청, feat

#7 [feat:#6] Generals 데이터 조회(General에 대한 Service, Repository,Controller 추가)
  build.gradle
  src/main/java/bokzip/back/SpringConfig.java
  src/main/java/bokzip/back/controller/GeneralController.java
  src/main/java/bokzip/back/repository/GeneralRepository.java
  src/main/java/bokzip/back/service/GeneralService.java
  src/main/resources/application.properties
Labels: 피드백 요청, feat

#8 [mod:#3] Posts 데이터 요청 값으로 return 변경
  build.gradle
  src/main/java/bokzip/back/configuration/DBConfig.java
  src/main/java/bokzip/back/controller/PostController.java
  src/main/java/bokzip/back/domain/General.java
  src/main/java/bokzip/back/domain/PersonalInfo.java
  src/main/java/bokzip/back/domain/Post.java
  src/main/java/bokzip/back/domain/Scrap.java
  src/main/java/bokzip/back/domain/User.java
  src/main/java/bokzip/back/dto/HomeResponseDto.java
  src/main/java/bokzip/back/repository/PostRepository.java
  src/main/java/bokzip/back/repository/UserRepository.java
  src/main/java/bokzip/back/service/PostService.java
  src/main/java/bokzip/back/service/UserService.java
  src/test/java/bokzip/back/repository/PostRepositroyTest.java
  src/test/java/bokzip/back/service/PostServiceTest.java
Labels: 피드백 요청, mod

#10 [feat#9#11] Logging처리, Banner 변경
  src/main/resources/banner.txt
  src/main/resources/logback.xml
Labels: 피드백 요청, feat

#14 [mod:#3]Posts 요청에 따른 응답코드 추가
  src/main/java/bokzip/back/controller/PostController.java
  src/main/java/bokzip/back/dto/ErrorResponse.java
Labels: 피드백 요청, 김혜정, mod

#13 [mod:#3] 중앙부처) 전체 데이터 조회 Id 값으로 정렬 추가
  src/main/java/bokzip/back/service/PostService.java
Labels: 김은서, mod

#15 [mod:#6]Generals 요청에 따른 응답코드 추가
  src/main/java/bokzip/back/controller/GeneralController.java
Labels: 피드백 요청, 김은서, mod

#16 [fix:#3] Posts 예외처리 수정
  .gitignore
  build.gradle
  src/main/java/bokzip/back/config/CustomException.java
  src/main/java/bokzip/back/config/ErrorCode.java
  src/main/java/bokzip/back/config/ErrorResponse.java
  src/main/java/bokzip/back/config/GlobalExceptionHandler.java
  src/main/java/bokzip/back/controller/PostController.java
  src/main/java/bokzip/back/domain/User.java
  src/main/java/bokzip/back/service/PostService.java
  src/main/resources/logback.xml
  src/test/java/bokzip/back/service/PostServiceTest.java
Labels: 피드백 요청, fix, 김혜정

#18 [feat:#17] Scrap 추가 및 해제
  src/main/java/bokzip/back/controller/ScrapController.java
  src/main/java/bokzip/back/domain/General.java
  src/main/java/bokzip/back/domain/Scrap.java
  src/main/java/bokzip/back/domain/ScrapType.java
  src/main/java/bokzip/back/dto/ScrapMapping.java
  src/main/java/bokzip/back/repository/ScrapRepository.java
  src/main/java/bokzip/back/service/ScrapService.java
Labels: 피드백 요청, feat, 김은서

#21 [mod:#3:#6:#17] Posts, Generals, Scraps 예외처리 추가
  build.gradle
  src/main/java/bokzip/back/config/CustomException.java
  src/main/java/bokzip/back/config/ErrorCode.java
  src/main/java/bokzip/back/config/GlobalExceptionHandler.java
  src/main/java/bokzip/back/config/SuccessResponse.java
  src/main/java/bokzip/back/controller/GeneralController.java
  src/main/java/bokzip/back/controller/PostController.java
  src/main/java/bokzip/back/controller/ScrapController.java
  src/main/java/bokzip/back/domain/Post.java
  src/main/java/bokzip/back/dto/HomeMapping.java
  src/main/java/bokzip/back/dto/HomeResponseDto.java
  src/main/java/bokzip/back/repository/GeneralRepository.java
  src/main/java/bokzip/back/repository/PostRepository.java
  src/main/java/bokzip/back/service/GeneralService.java
  src/main/java/bokzip/back/service/PostService.java
  src/main/java/bokzip/back/service/ScrapService.java
  src/main/resources/application.properties
  src/test/java/bokzip/back/repository/PostRepositroyTest.java
  src/test/java/bokzip/back/service/PostServiceTest.java
Labels: test, refact, fix, 김혜정, mod

#22 [mod:#4#6#17]
  src/main/java/bokzip/back/controller/GeneralController.java
  src/main/java/bokzip/back/domain/General.java
  src/main/java/bokzip/back/domain/Post.java
  src/main/java/bokzip/back/service/GeneralService.java
  src/main/java/bokzip/back/service/ScrapService.java
Labels: 피드백 요청, 김은서, mod

#24 [mod:#3] Post 데이터 return value 수정
  src/main/java/bokzip/back/config/CustomException.java
  src/main/java/bokzip/back/config/ErrorCode.java
  src/main/java/bokzip/back/config/GlobalExceptionHandler.java
  src/main/java/bokzip/back/config/SuccessResponse.java
  src/main/java/bokzip/back/controller/GeneralController.java
  src/main/java/bokzip/back/controller/PostController.java
  src/main/java/bokzip/back/controller/ScrapController.java
  src/main/java/bokzip/back/domain/General.java
  src/main/java/bokzip/back/domain/Post.java
  src/main/java/bokzip/back/dto/ErrorResponse.java
  src/main/java/bokzip/back/dto/HomeResponseDto.java
  src/main/java/bokzip/back/dto/PostMapping.java
  src/main/java/bokzip/back/dto/ScrapMapping.java
  src/main/java/bokzip/back/repository/GeneralRepository.java
  src/main/java/bokzip/back/repository/PostRepository.java
  src/main/java/bokzip/back/service/GeneralService.java
  src/main/java/bokzip/back/service/PostService.java
  src/main/java/bokzip/back/service/ScrapService.java
  src/main/resources/application.properties
  src/test/java/bokzip/back/repository/PostRepositroyTest.java
  src/test/java/bokzip/back/service/PostServiceTest.java
Labels: 피드백 요청, fix, 김혜정, mod

#23 [mod#6] 인기순, 조회순 정렬
  src/main/java/bokzip/back/controller/GeneralController.java
  src/main/java/bokzip/back/dto/GeneralMapping.java
  src/main/java/bokzip/back/repository/GeneralRepository.java
  src/main/java/bokzip/back/service/GeneralService.java
Labels: 피드백 요청, 김은서, mod
