Repository bokzip/bokzip-backend, pull requests merged in 2021-10, with the labels that each got.

#35 [feat:#34] Heroku와 RDS 연결을 위해 관련 파일 수정
  build.gradle
  src/main/resources/application.properties
Labels: 피드백 요청, fix, 김혜정

#36 [feat:#20] Security 활용한 구글 로그인 구현 & [refact#17] 스크랩 구현
  build.gradle
  src/main/java/bokzip/back/config/CustomOAuth2UserService.java
  src/main/java/bokzip/back/config/ErrorCode.java
  src/main/java/bokzip/back/config/GlobalExceptionHandler.java
  src/main/java/bokzip/back/config/OAuthAttributes.java
  src/main/java/bokzip/back/config/SecurityConfig.java
  src/main/java/bokzip/back/config/UserConverter.java
  src/main/java/bokzip/back/controller/ScrapController.java
  src/main/java/bokzip/back/domain/General.java
  src/main/java/bokzip/back/domain/Post.java
  src/main/java/bokzip/back/domain/Provider.java
  src/main/java/bokzip/back/domain/Scrap.java
  src/main/java/bokzip/back/domain/User.java
  src/main/java/bokzip/back/dto/PostDto.java
  src/main/java/bokzip/back/dto/UserDto.java
  src/main/java/bokzip/back/repository/UserRepository.java
  src/main/java/bokzip/back/service/ScrapService.java
Labels: 피드백 요청, feat, 김은서

#40 CI/CD 구현한 yml 파일을 pr 올립니다!
  .github/workflows/CICD.yml
Labels: 피드백 요청, feat, 김혜정
